[package]
name = "easy-deploy"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17.8"
structopt = "0.3.26"
solana-program = "2.0.14"
solana-sdk = "2.0.14"
solana-client = "2.0.14"
env_logger = "0.11.5"
log = "0.4.22"

